// Authentic Full Offline Tribal Corpus for Santhali, Ho, and Mundari Languages
// Specially curated for Mother Tongue-Based Multilingual Education (MTB-MLE) in Jharkhand

export const TRIBAL_LANGUAGES = [
  { 
    id: "santhali", 
    name: "Santhali (ᱥᱟᱱᱛᱟᱲᱤ)", 
    nativeScript: "Ol Chiki (ᱚᱞ ᱪᱤᱠᱤ)", 
    scriptName: "Ol Chiki / Devanagari", 
    region: "Santhal Pargana (Dumka, Deoghar, Godda, Jamtara, Pakur, Sahibganj)",
    family: "Austroasiatic (Munda)",
    color: "from-amber-500 to-orange-600"
  },
  { 
    id: "ho", 
    name: "Ho (ᱦᱳ / हो)", 
    nativeScript: "Warang Citi (𑢹𑣉𑣉 / वारंग चिति)", 
    scriptName: "Warang Citi / Devanagari", 
    region: "Kolhan Division (West Singhbhum, East Singhbhum, Saraikela)",
    family: "Austroasiatic (Munda)",
    color: "from-emerald-500 to-teal-600"
  },
  { 
    id: "mundari", 
    name: "Mundari (मुण्डारी / ᱢᱩᱱᱰᱟᱨᱤ)", 
    nativeScript: "Mundari Bani / Devanagari (मुण्डारी)", 
    scriptName: "Devanagari / Mundari Bani", 
    region: "Ranchi, Khunti, Gumla, Simdega",
    family: "Austroasiatic (Munda)",
    color: "from-blue-500 to-indigo-600"
  }
];

export const CLASSROOM_PHRASES = [
  {
    id: "cp_1",
    category: "greeting",
    hindi: "नमस्ते बच्चों, आप सब कैसे हैं?",
    santhali_olchiki: "ᱡᱚᱦᱟᱨ ᱜᱤᱫᱽᱨᱟᱹ ᱠᱚ, ᱟᱯᱮ ᱪᱮᱫ ᱞᱮᱠᱟ ᱢᱮᱱᱟᱜ ᱯᱮᱭᱟ?",
    santhali_devanagari: "जोहार गिद्रा को, आपे चेद लेका मेनाग पेया?",
    santhali_phonetic: "Johar gidra ko, aape ched leka menag peya?",
    ho_devanagari: "जोहार हुनको, आपे चिलका मेनापिया?",
    ho_phonetic: "Johar hunko, aape chilka menapiya?",
    mundari_devanagari: "जोहार होनको, आपे चिलेका मेनापिया?",
    mundari_phonetic: "Johar honko, aape chileka menapiya?",
    english: "Hello children, how are you all?"
  },
  {
    id: "cp_2",
    category: "instruction",
    hindi: "कृपया अपनी किताब खोलिए।",
    santhali_olchiki: "ᱫᱟᱭᱟᱠᱟᱛᱮ ᱟᱢᱟᱜ ᱯᱚᱛᱚᱵ ᱡᱷᱤᱡᱽ ᱢᱮ᱾",
    santhali_devanagari: "दायाकाते आमाग पोतोब झिज मे।",
    santhali_phonetic: "Dayakate aamag potob jhij me.",
    ho_devanagari: "दायाकिते आमा पुथी निड़ में।",
    ho_phonetic: "Dayakite aama puthi nir men.",
    mundari_devanagari: "दायाकिते आमाः पोथी निड़ में।",
    mundari_phonetic: "Dayakite aamaah pothi nir men.",
    english: "Please open your book."
  },
  {
    id: "cp_3",
    category: "instruction",
    hindi: "सभी बच्चे अपनी जगह पर बैठ जाओ।",
    santhali_olchiki: "ᱥᱟᱱᱟᱢ ᱜᱤᱫᱽᱨᱟᱹ ᱟᱯᱱᱟᱨ ᱴᱷᱟᱶ ᱨᱮ ᱫᱩᱲᱩᱵ ᱯᱮ᱾",
    santhali_devanagari: "सानाम गिद्रा आपनार ठांव रे दुड़ुब पे।",
    santhali_phonetic: "Sanam gidra apnar thaw re durub pe.",
    ho_devanagari: "सोबेन हुनको आपना जागा रे दुब पे।",
    ho_phonetic: "Soben hunko aapna jaaga re dub pe.",
    mundari_devanagari: "सोबेन होनको आपनाः ठांव रे दुब पे।",
    mundari_phonetic: "Soben honko aapnaah thaonw re dub pe.",
    english: "All children please sit down at your places."
  },
  {
    id: "cp_4",
    category: "encouragement",
    hindi: "बहुत बढ़िया! आपने बहुत अच्छा किया।",
    santhali_olchiki: "ᱟᱹᱰᱤ ᱱᱟᱯᱟᱭ! ᱟᱢ ᱟᱹᱰᱤ ᱵᱷᱟᱹᱜᱤᱢ ᱠᱟᱹᱢᱤ ᱠᱮᱫᱟ᱾",
    santhali_devanagari: "आडी नापाय! आम आडी भागीम कामी केदा।",
    santhali_phonetic: "Adi napay! Aam adi bhagim kami keda.",
    ho_devanagari: "एतों बगे! आम एतों बगेम बाई केदा।",
    ho_phonetic: "Eton bage! Aam eton bagem baai keda.",
    mundari_devanagari: "एतों बुगि! आम एतों बुगिम बाई केदा।",
    mundari_phonetic: "Eton bugi! Aam eton bugim baai keda.",
    english: "Very good! You did very well."
  },
  {
    id: "cp_5",
    category: "question",
    hindi: "क्या आपको समझ आया?",
    santhali_olchiki: "ᱪᱮᱫ ᱟᱢ ᱵᱩᱡᱷᱟᱹᱣ ᱠᱮᱫᱟ?",
    santhali_devanagari: "चेद आम बुझाव केदा?",
    santhali_phonetic: "Ched aam bujhaw keda?",
    ho_devanagari: "चिना आम बुझौ केदा?",
    ho_phonetic: "China aam bujhow keda?",
    mundari_devanagari: "चिनाः आम बुझौ केदा?",
    mundari_phonetic: "Chinaah aam bujhow keda?",
    english: "Did you understand?"
  },
  {
    id: "cp_6",
    category: "instruction",
    hindi: "श्यामपट्ट की ओर देखो।",
    santhali_olchiki: "ᱵᱽᱞᱮᱠᱵᱳᱨᱰ ᱥᱮᱫ ᱠᱚᱭᱚᱜᱽ ᱢᱮ᱾",
    santhali_devanagari: "ब्लैकबोर्ड सेद कोयॉग मे।",
    santhali_phonetic: "Blackboard sed koyog me.",
    ho_devanagari: "बोर्ड पा मुतुन में।",
    ho_phonetic: "Board paa mutun men.",
    mundari_devanagari: "बोर्ड पा मुतुन में।",
    mundari_phonetic: "Board paa mutun men.",
    english: "Look towards the blackboard."
  },
  {
    id: "cp_7",
    category: "dialogue",
    hindi: "तुम्हारा नाम क्या है?",
    santhali_olchiki: "ᱟᱢᱟᱜ ᱧᱩᱛᱩᱢ ᱫᱚ ᱪᱮᱫ?",
    santhali_devanagari: "आमाग ञुतुम दो चेद?",
    santhali_phonetic: "Aamag nyutum do ched?",
    ho_devanagari: "आमा नुतुम चिना?",
    ho_phonetic: "Aama nutum china?",
    mundari_devanagari: "अम-आः नुतुम चिनाः?",
    mundari_phonetic: "Am-aah nutum chinaah?",
    english: "What is your name?"
  },
  {
    id: "cp_8",
    category: "dialogue",
    hindi: "मेरा नाम बिरसा है।",
    santhali_olchiki: "ᱤᱧᱟᱜ ᱧᱩᱛᱩᱢ ᱫᱚ ᱵᱤᱨᱥᱟ ᱠᱟᱱᱟ᱾",
    santhali_devanagari: "इञाग ञुतुम दो बिरसा काना।",
    santhali_phonetic: "Inyag nyutum do Birsa kana.",
    ho_devanagari: "आईंग-आ नुतुम बिरसा ताना।",
    ho_phonetic: "Aying-aa nutum Birsa tana.",
    mundari_devanagari: "आईंग-आः नुतुम बिरसा तनाः।",
    mundari_phonetic: "Aying-aah nutum Birsa tanaah.",
    english: "My name is Birsa."
  },
  {
    id: "cp_9",
    category: "instruction",
    hindi: "हाथ ऊपर करो।",
    santhali_olchiki: "ᱛᱤ ᱪᱮᱛᱟᱱ ᱨᱟᱠᱟᱵᱽ ᱢᱮ᱾",
    santhali_devanagari: "ती चेतान राकाब मे।",
    santhali_phonetic: "Ti chetan rakab me.",
    ho_devanagari: "ती चेतान रे राकाये में।",
    ho_phonetic: "Ti chetan re rakaaye men.",
    mundari_devanagari: "ती चेतान रे राकाये में।",
    mundari_phonetic: "Ti chetan re rakaaye men.",
    english: "Raise your hand up."
  },
  {
    id: "cp_10",
    category: "instruction",
    hindi: "चलो एक साथ मिलकर गाते हैं।",
    santhali_olchiki: "ᱫᱮᱞᱟᱵᱚᱱ ᱢᱤᱫ ᱥᱟᱶᱛᱮ ᱥᱮᱨᱮᱧᱟᱵᱚᱱ᱾",
    santhali_devanagari: "देलाबोन मिद सांवते सेरेञाबोन।",
    santhali_phonetic: "Delabon mid sawte serenj-abon.",
    ho_devanagari: "दुरांग मिद ते दूरंग लेबु।",
    ho_phonetic: "Durang mid te durang lebu.",
    mundari_devanagari: "दुरांग मिद ते दूरंग लेबु।",
    mundari_phonetic: "Durang mid te durang lebu.",
    english: "Come, let us sing together."
  },
  {
    id: "cp_11",
    category: "instruction",
    hindi: "शांति से बैठो और सुनो।",
    santhali_olchiki: "ᱛᱷᱤᱨ ᱠᱟᱛᱮ ᱫᱩᱲᱩᱵ ᱢᱮ ᱟᱨ ᱟᱸᱡᱚᱢ ᱢᱮ᱾",
    santhali_devanagari: "थिर काते दुड़ुब मे आर आंजोम मे।",
    santhali_phonetic: "Thir kate durub me aar anjom me.",
    ho_devanagari: "थिर ते दुब में आर आयुम में।",
    ho_phonetic: "Thir te dub men aar aayum men.",
    mundari_devanagari: "सुस्त ते दुब में आर आजोम में।",
    mundari_phonetic: "Sust te dub men aar aajom men.",
    english: "Sit quietly and listen."
  },
  {
    id: "cp_12",
    category: "encouragement",
    hindi: "डरो मत, तुम यह कर सकते हो।",
    santhali_olchiki: "ᱟᱞᱚᱢ ᱵᱚᱛᱚᱨᱚᱜᱼᱟ, ᱟᱢ ᱱᱚᱣᱟᱢ ᱫᱟᱲᱮᱭᱟᱜᱼᱟ᱾",
    santhali_devanagari: "आलोम बोतोरोग-आ, आम नोवाम दाड़ेयाग-आ।",
    santhali_phonetic: "Alom botorog-a, aam nowam dareyag-a.",
    ho_devanagari: "आलोम बोतोरो, आम नेया दाइयेआ।",
    ho_phonetic: "Aalom botoro, aam neya daaiye-aa.",
    mundari_devanagari: "आलोम बोतोरो, आम नेया दाइयेआ।",
    mundari_phonetic: "Aalom botoro, aam neya daaiye-aa.",
    english: "Do not be afraid, you can do this."
  },
  {
    id: "cp_13",
    category: "subject_science",
    hindi: "पौधे सूर्य के प्रकाश से भोजन बनाते हैं।",
    santhali_olchiki: "ᱫᱟᱨᱮ ᱱᱟᱹᱬᱤ ᱥᱤᱧ ᱪᱟᱸᱫᱳ ᱛᱟᱨᱟᱥ ᱛᱮ ᱡᱚᱢᱟᱜ ᱠᱚ ᱛᱮᱭᱟᱨᱟ᱾",
    santhali_devanagari: "दारे नाड़ी सिञ चांदो तारास ते जोमाग को तेयारा।",
    santhali_phonetic: "Dare nari sinj chando taras te jomag ko teyara.",
    ho_devanagari: "दारु को सिंगी मारशाल ते जोमतेया बाई-या।",
    ho_phonetic: "Daru ko singi marshaal te jomteya baai-ya.",
    mundari_devanagari: "दारु को सिंगी मारशाल ते जोमतेया बाई-या।",
    mundari_phonetic: "Daru ko singi marshaal te jomteya baai-ya.",
    english: "Plants make food from sunlight (Photosynthesis)."
  },
  {
    id: "cp_14",
    category: "subject_math",
    hindi: "दो और दो जोड़ने पर चार होते हैं।",
    santhali_olchiki: "ᱵᱟᱨ ᱟᱨ ᱵᱟᱨ ᱢᱮᱥᱟ ᱞᱮᱠᱷᱟᱱ ᱯᱳᱱ ᱦᱩᱭᱩᱜᱼᱟ᱾",
    santhali_devanagari: "बार आर बार मेसा लेखान पोन हुयुग-आ।",
    santhali_phonetic: "Bar aar bar mesa lekhan pon huyug-a.",
    ho_devanagari: "बारिया आर बारिया मिसा लेरे उपूनिया हुबाओ-आ।",
    ho_phonetic: "Bariya aar bariya misa lere upuniya hubao-aa.",
    mundari_devanagari: "बारिया आर बारिया मिसा लेरे उपूनिया होबो-आ।",
    mundari_phonetic: "Bariya aar bariya misa lere upuniya hobo-aa.",
    english: "Two plus two equals four."
  },
  {
    id: "cp_15",
    category: "subject_evs",
    hindi: "जल ही जीवन है, हमें पानी बचाना चाहिए।",
    santhali_olchiki: "ᱫᱟᱜ ᱜᱮ ᱡᱤᱣᱤ ᱠᱟᱱᱟ, ᱟᱵᱚ ᱫᱟᱜ ᱵᱟᱧᱪᱟᱣ ᱫᱚᱨᱠᱟᱨ᱾",
    santhali_devanagari: "दाग गे जीवी काना, आबो दाग बांचाव दोरकार।",
    santhali_phonetic: "Daag ge jiwi kana, aabo daag banchaw dorkar.",
    ho_devanagari: "दाः गे जिउ ताना, आबु दाः बांचाव होबाओ-आ।",
    ho_phonetic: "Daah ge jiu tana, aabu daah banchaaw hobao-aa.",
    mundari_devanagari: "दाः गे जिउ तनाः, आबु दाः बांचाव होबाओ-आ।",
    mundari_phonetic: "Daah ge jiu tanaah, aabu daah banchaaw hobao-aa.",
    english: "Water is life, we must save water."
  },
  {
    id: "cp_16",
    category: "question",
    hindi: "गुरुजी, मुझे एक सवाल पूछना है।",
    santhali_olchiki: "ᱜᱚᱢᱠᱮ, ᱤᱧ ᱢᱤᱫᱴᱟᱝ ᱠᱩᱠᱞᱤ ᱠᱩᱞᱤ ᱥᱟᱱᱟᱹᱧ ᱠᱟᱱᱟ᱾",
    santhali_devanagari: "गोमके, इञ मिदटांग कुकली कुली सानाइञ काना।",
    santhali_phonetic: "Gomke, iny midtang kukli kuli sanainy kana.",
    ho_devanagari: "गुरुजी, आईंग मियद कुली कुली सानाईंग ताना।",
    ho_phonetic: "Guruji, aying miyad kuli kuli sanaaying tana.",
    mundari_devanagari: "गुरुजी, आईंग मियाद कुली कुली सानाईंग तनाः।",
    mundari_phonetic: "Guruji, aying miyaad kuli kuli sanaaying tanaah.",
    english: "Teacher, I want to ask a question."
  }
];

export const VOCABULARY_LIST = [
  // Numbers (1-10)
  {
    id: "v_1",
    category: "numbers",
    hindi: "एक (1)",
    santhali_olchiki: "ᱢᱤᱫ (᱑)",
    santhali_devanagari: "मिद",
    santhali_phonetic: "Mid",
    ho_devanagari: "मियद",
    ho_phonetic: "Miyad",
    mundari_devanagari: "मियाद",
    mundari_phonetic: "Miyaad",
    english: "One",
    icon: "1️⃣"
  },
  {
    id: "v_2",
    category: "numbers",
    hindi: "दो (2)",
    santhali_olchiki: "ᱵᱟᱨ (᱒)",
    santhali_devanagari: "बार",
    santhali_phonetic: "Bar",
    ho_devanagari: "बारिया",
    ho_phonetic: "Bariya",
    mundari_devanagari: "बारिया",
    mundari_phonetic: "Bariya",
    english: "Two",
    icon: "2️⃣"
  },
  {
    id: "v_3",
    category: "numbers",
    hindi: "तीन (3)",
    santhali_olchiki: "ᱯᱮ (᱓)",
    santhali_devanagari: "पे",
    santhali_phonetic: "Pe",
    ho_devanagari: "आपिया",
    ho_phonetic: "Aapiya",
    mundari_devanagari: "आपिया",
    mundari_phonetic: "Aapiya",
    english: "Three",
    icon: "3️⃣"
  },
  {
    id: "v_4",
    category: "numbers",
    hindi: "चार (4)",
    santhali_olchiki: "ᱯᱳᱱ (᱔)",
    santhali_devanagari: "पोन",
    santhali_phonetic: "Pon",
    ho_devanagari: "उपूनिया",
    ho_phonetic: "Upuniya",
    mundari_devanagari: "उपूनिया",
    mundari_phonetic: "Upuniya",
    english: "Four",
    icon: "4️⃣"
  },
  {
    id: "v_5",
    category: "numbers",
    hindi: "पाँच (5)",
    santhali_olchiki: "ᱢᱚᱬᱮ (᱕)",
    santhali_devanagari: "मोणे",
    santhali_phonetic: "Mone",
    ho_devanagari: "मोड़ेया",
    ho_phonetic: "Modeya",
    mundari_devanagari: "मोड़ेया",
    mundari_phonetic: "Modeya",
    english: "Five",
    icon: "5️⃣"
  },
  {
    id: "v_6",
    category: "numbers",
    hindi: "छह (6)",
    santhali_olchiki: "ᱛᱩᱨᱩᱭ (᱖)",
    santhali_devanagari: "तुरुय",
    santhali_phonetic: "Turuy",
    ho_devanagari: "तुरिया",
    ho_phonetic: "Turiya",
    mundari_devanagari: "तुरिया",
    mundari_phonetic: "Turiya",
    english: "Six",
    icon: "6️⃣"
  },
  {
    id: "v_7",
    category: "numbers",
    hindi: "सात (7)",
    santhali_olchiki: "ᱮᱭᱟᱭ (᱗)",
    santhali_devanagari: "एयाय",
    santhali_phonetic: "Eyay",
    ho_devanagari: "एया",
    ho_phonetic: "Eya",
    mundari_devanagari: "एया",
    mundari_phonetic: "Eya",
    english: "Seven",
    icon: "7️⃣"
  },
  {
    id: "v_8",
    category: "numbers",
    hindi: "आठ (8)",
    santhali_olchiki: "ᱤᱨᱟᱹᱞ (᱘)",
    santhali_devanagari: "इरल",
    santhali_phonetic: "Iral",
    ho_devanagari: "इरलिया",
    ho_phonetic: "Iraliya",
    mundari_devanagari: "इरलिया",
    mundari_phonetic: "Iraliya",
    english: "Eight",
    icon: "8️⃣"
  },
  {
    id: "v_9",
    category: "numbers",
    hindi: "नौ (9)",
    santhali_olchiki: "ᱟᱨᱮ (᱙)",
    santhali_devanagari: "आरे",
    santhali_phonetic: "Aare",
    ho_devanagari: "आरेया",
    ho_phonetic: "Aareya",
    mundari_devanagari: "आरेया",
    mundari_phonetic: "Aareya",
    english: "Nine",
    icon: "9️⃣"
  },
  {
    id: "v_10",
    category: "numbers",
    hindi: "दस (10)",
    santhali_olchiki: "ᱜᱮᱞ (᱑᱐)",
    santhali_devanagari: "गेल",
    santhali_phonetic: "Gel",
    ho_devanagari: "गेलेया",
    ho_phonetic: "Geleya",
    mundari_devanagari: "गेलेया",
    mundari_phonetic: "Geleya",
    english: "Ten",
    icon: "🔟"
  },

  // Nature & Environment
  {
    id: "v_11",
    category: "nature",
    hindi: "पेड़ / वृक्ष",
    santhali_olchiki: "ᱫᱟᱨᱮ",
    santhali_devanagari: "दारे",
    santhali_phonetic: "Dare",
    ho_devanagari: "दारु",
    ho_phonetic: "Daru",
    mundari_devanagari: "दारु",
    mundari_phonetic: "Daru",
    english: "Tree",
    icon: "🌳"
  },
  {
    id: "v_12",
    category: "nature",
    hindi: "पानी / जल",
    santhali_olchiki: "ᱫᱟᱜ",
    santhali_devanagari: "दाग",
    santhali_phonetic: "Daag",
    ho_devanagari: "दाः",
    ho_phonetic: "Daah",
    mundari_devanagari: "दाः",
    mundari_phonetic: "Daah",
    english: "Water",
    icon: "💧"
  },
  {
    id: "v_13",
    category: "nature",
    hindi: "सूर्य / सूरज",
    santhali_olchiki: "ᱥᱤᱧ ᱪᱟᱸᱫᱳ",
    santhali_devanagari: "सिञ चांदो",
    santhali_phonetic: "Sinj Chando",
    ho_devanagari: "सिंगी",
    ho_phonetic: "Singi",
    mundari_devanagari: "सिंगी",
    mundari_phonetic: "Singi",
    english: "Sun",
    icon: "☀️"
  },
  {
    id: "v_14",
    category: "nature",
    hindi: "चंद्रमा / चाँद",
    santhali_olchiki: "ᱧᱤᱫᱟᱹ ᱪᱟᱸᱫᱳ",
    santhali_devanagari: "ञिदा चांदो",
    santhali_phonetic: "Nyida Chando",
    ho_devanagari: "चांदू",
    ho_phonetic: "Chandu",
    mundari_devanagari: "चांदू",
    mundari_phonetic: "Chandu",
    english: "Moon",
    icon: "🌙"
  },
  {
    id: "v_15",
    category: "nature",
    hindi: "फूल (पलाश)",
    santhali_olchiki: "ᱵᱟᱦᱟ (ᱯᱟᱞᱟᱥ)",
    santhali_devanagari: "बाहा (पलाश)",
    santhali_phonetic: "Baha (Palash)",
    ho_devanagari: "बा",
    ho_phonetic: "Baa",
    mundari_devanagari: "बा",
    mundari_phonetic: "Baa",
    english: "Flower (Palash)",
    icon: "🌺"
  },
  {
    id: "v_16",
    category: "nature",
    hindi: "पत्ता / पत्ती",
    santhali_olchiki: "ᱥᱟᱠᱟᱢ",
    santhali_devanagari: "साकाम",
    santhali_phonetic: "Sakam",
    ho_devanagari: "साकम",
    ho_phonetic: "Sakam",
    mundari_devanagari: "साकम",
    mundari_phonetic: "Sakam",
    english: "Leaf",
    icon: "🍃"
  },
  {
    id: "v_17",
    category: "nature",
    hindi: "जंगल / वन",
    santhali_olchiki: "ᱵᱤᱨ",
    santhali_devanagari: "बीर",
    santhali_phonetic: "Bir",
    ho_devanagari: "बुरु / बीर",
    ho_phonetic: "Buru / Bir",
    mundari_devanagari: "बीर",
    mundari_phonetic: "Bir",
    english: "Forest",
    icon: "🌲"
  },

  // Animals
  {
    id: "v_18",
    category: "animals",
    hindi: "पक्षी / चिड़िया",
    santhali_olchiki: "ᱪᱮᱬᱮ",
    santhali_devanagari: "चेणे",
    santhali_phonetic: "Chene",
    ho_devanagari: "चेणे",
    ho_phonetic: "Chene",
    mundari_devanagari: "चेड़े",
    mundari_phonetic: "Chede",
    english: "Bird",
    icon: "🐦"
  },
  {
    id: "v_19",
    category: "animals",
    hindi: "हाथी",
    santhali_olchiki: "ᱦᱟᱹᱛᱤ",
    santhali_devanagari: "हाती",
    santhali_phonetic: "Hati",
    ho_devanagari: "हाती",
    ho_phonetic: "Hati",
    mundari_devanagari: "हाती",
    mundari_phonetic: "Hati",
    english: "Elephant",
    icon: "🐘"
  },
  {
    id: "v_20",
    category: "animals",
    hindi: "गाय",
    santhali_olchiki: "ᱜᱟᱹᱭ",
    santhali_devanagari: "गई",
    santhali_phonetic: "Gayi",
    ho_devanagari: "गाई",
    ho_phonetic: "Gaai",
    mundari_devanagari: "उरीः",
    mundari_phonetic: "Urih",
    english: "Cow",
    icon: "🐄"
  },
  {
    id: "v_21",
    category: "animals",
    hindi: "मछली",
    santhali_olchiki: "ᱦᱟᱠᱳ",
    santhali_devanagari: "हाको",
    santhali_phonetic: "Hako",
    ho_devanagari: "हाकु",
    ho_phonetic: "Haku",
    mundari_devanagari: "हाकु",
    mundari_phonetic: "Haku",
    english: "Fish",
    icon: "🐟"
  },
  {
    id: "v_22",
    category: "animals",
    hindi: "बाघ / शेर",
    santhali_olchiki: "ᱛᱟᱹᱨᱩᱵ",
    santhali_devanagari: "तारुब",
    santhali_phonetic: "Tarub",
    ho_devanagari: "कुला",
    ho_phonetic: "Kula",
    mundari_devanagari: "कुला",
    mundari_phonetic: "Kula",
    english: "Tiger / Leopard",
    icon: "🐅"
  },

  // School & Learning
  {
    id: "v_23",
    category: "school",
    hindi: "किताब / पुस्तक",
    santhali_olchiki: "ᱯᱚᱛᱚᱵ",
    santhali_devanagari: "पोतोब",
    santhali_phonetic: "Potob",
    ho_devanagari: "पुथी",
    ho_phonetic: "Puthi",
    mundari_devanagari: "पोथी",
    mundari_phonetic: "Pothi",
    english: "Book",
    icon: "📖"
  },
  {
    id: "v_24",
    category: "school",
    hindi: "कलम / पेन",
    santhali_olchiki: "ᱠᱚᱞᱚᱢ",
    santhali_devanagari: "कोलोम",
    santhali_phonetic: "Kolom",
    ho_devanagari: "कलम",
    ho_phonetic: "Kalam",
    mundari_devanagari: "कलम",
    mundari_phonetic: "Kalam",
    english: "Pen / Pencil",
    icon: "✏️"
  },
  {
    id: "v_25",
    category: "school",
    hindi: "विद्यालय / स्कूल",
    santhali_olchiki: "ᱤᱛᱩᱱ ᱟᱥᱲᱟ",
    santhali_devanagari: "इतून आसड़ा",
    santhali_phonetic: "Itun Asra",
    ho_devanagari: "इस्कूल / आसड़ा",
    ho_phonetic: "Iskul / Asra",
    mundari_devanagari: "आसड़ा / स्कूल",
    mundari_phonetic: "Asra / School",
    english: "School",
    icon: "🏫"
  },
  {
    id: "v_26",
    category: "school",
    hindi: "शिक्षक / गुरुजी",
    santhali_olchiki: "ᱜᱚᱢᱠᱮ / ᱢᱟᱪᱮᱫ",
    santhali_devanagari: "गोमके / माचेद",
    santhali_phonetic: "Gomke / Mached",
    ho_devanagari: "गुरुजी / माचेत",
    ho_phonetic: "Guruji / Machet",
    mundari_devanagari: "गुरुजी / माचेत",
    mundari_phonetic: "Guruji / Machet",
    english: "Teacher",
    icon: "👨‍🏫"
  },
  {
    id: "v_27",
    category: "school",
    hindi: "घर / आवास",
    santhali_olchiki: "ᱚᱲᱟᱜ",
    santhali_devanagari: "ओड़ाग",
    santhali_phonetic: "Orag",
    ho_devanagari: "ओड़ाः",
    ho_phonetic: "Oraah",
    mundari_devanagari: "ओड़ाः",
    mundari_phonetic: "Oraah",
    english: "Home / House",
    icon: "🏠"
  },

  // Family & Relations
  {
    id: "v_28",
    category: "family",
    hindi: "माँ / माता",
    santhali_olchiki: "ᱟᱭᱳ",
    santhali_devanagari: "आयो",
    santhali_phonetic: "Ayo",
    ho_devanagari: "एंगा",
    ho_phonetic: "Enga",
    mundari_devanagari: "एंगा",
    mundari_phonetic: "Enga",
    english: "Mother",
    icon: "👩‍👧"
  },
  {
    id: "v_29",
    category: "family",
    hindi: "पिता / बाबा",
    santhali_olchiki: "ᱵᱟᱵᱟ",
    santhali_devanagari: "बाबा",
    santhali_phonetic: "Baba",
    ho_devanagari: "आपा",
    ho_phonetic: "Aapa",
    mundari_devanagari: "आपु",
    mundari_phonetic: "Aapu",
    english: "Father",
    icon: "👨‍👦"
  },
  {
    id: "v_30",
    category: "family",
    hindi: "दोस्त / मित्र",
    santhali_olchiki: "ᱜᱟᱛᱮ",
    santhali_devanagari: "गाते",
    santhali_phonetic: "Gate",
    ho_devanagari: "गाति",
    ho_phonetic: "Gaati",
    mundari_devanagari: "गाति",
    mundari_phonetic: "Gaati",
    english: "Friend",
    icon: "🤝"
  }
];
